# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'canvas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 20, 541, 511))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = Canvas(self.horizontalLayoutWidget)
        self.frame.setMinimumSize(QtCore.QSize(200, 0))
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.list_nodes = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.list_nodes.setObjectName("list_nodes")
        self.verticalLayout.addWidget(self.list_nodes)
        self.input_line = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.input_line.setObjectName("input_line")
        self.verticalLayout.addWidget(self.input_line)
        self.delete_nodes = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.delete_nodes.setObjectName("delete_nodes")
        self.verticalLayout.addWidget(self.delete_nodes)
        self.place_nodes = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.place_nodes.setObjectName("place_nodes")
        self.verticalLayout.addWidget(self.place_nodes)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.delete_nodes.setText(_translate("MainWindow", "Удалить все точки"))
        self.place_nodes.setText(_translate("MainWindow", "Построить график"))
from canvas import Canvas
